### ISSUE TITLE
Unable to import due to camelcase-keys

### ISSUE THREAD

**Issue by piedar** [gridcat/gridcoin-rpc#55]
Importing `gridcoin-rpc@4.0.1` from an ESM script fails with this error, but `gridcoin-rpc@4.0.0` works correctly.

```
/home/benn/code/barney/node_modules/gridcoin-rpc/dist/RPCBase.js:16
const camelcase_keys_1 = __importDefault(require("camelcase-keys"));
                                         ^

Error [ERR_REQUIRE_ESM]: require() of ES Module /home/benn/code/barney/node_modules/camelcase-keys/index.js from /home/benn/code/barney/node_modules/gridcoin-rpc/dist/RPCBase.js not supported.
Instead change the require of index.js in /home/benn/code/barney/node_modules/gridcoin-rpc/dist/RPCBase.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/home/benn/code/barney/node_modules/gridcoin-rpc/dist/RPCBase.js:16:42)
    at Object.<anonymous> (/home/benn/code/barney/node_modules/gridcoin-rpc/dist/RPC/Developer.js:13:19)
    at Object.<anonymous> (/home/benn/code/barney/node_modules/gridcoin-rpc/dist/GridcoinRPC.js:5:21)
    at async file:///home/benn/code/barney/bin/barney.mjs:7:25 {
  code: 'ERR_REQUIRE_ESM'
}

Node.js v20.6.1
```

 It looks like [`camelcase-keys@8.0.0`](https://github.com/sindresorhus/camelcase-keys/releases/tag/v8.0.0) moved away from commonjs but typescript is still trying to `require()` it.  I think your tsconfig.json should set `"module": "node16"` as [recommended by the typescript handbook](https://www.typescriptlang.org/docs/handbook/modules/reference.html#node16-nodenext).  As far as I can tell, this will automatically detect each module type and emit the appropriate `require()` or `import`.

**Comment by gridcat** [comment]
Sorry it took so long
